package io.bloomish.api.engine.initialization.initializer;

import io.bloomish.api.engine.context.ObjectRegistry;
import io.bloomish.api.engine.registry.factory.*;

import java.util.Collection;
import java.util.List;

public class FactoryInitializer implements ObjectRegistryInitializer {
    @Override
    public void initialize(Collection<Class<?>> classes, List<?> externalObjects, ObjectRegistry objectRegistry) {
        objectRegistry.registerAllValues(
                new ItemFactory(),
                new BlockFactory(),
                new ActivityFactory(),
                new ArmorMaterialFactory(),
                new AttachmentTypeFactory(),
                new AttributeFactory(),
                new BiomeModifierSerializerFactory(),
                new BiomeSourceFactory(),
                new BlockEntityTypeFactory(),
                new BlockPredicateTypeFactory(),
                new BlockStateProviderTypeFactory(),
                new BlockTypeFactory(),
                new CarverFactory(),
                new ChunkGeneratorFactory(),
                new CommandArgumentTypeFactory(),
                new ConditionCodecFactory(),
                new CreativeModeTabFactory(),
                new CustomStatFactory(),
                new DataComponentTypeFactory(),
                new DensityFunctionTypeFactory(),
                new EnchantmentEffectComponentTypeFactory(),
                new EnchantmentEntityEffectTypeFactory(),
                new EnchantmentLevelBasedValueTypeFactory(),
                new EnchantmentLocationBasedEffectTypeFactory(),
                new EnchantmentProviderTypeFactory(),
                new EnchantmentValueEffectTypeFactory(),
                new EntityDataSerializerFactory(),
                new EntitySubPredicateTypeFactory(),
                new EntityTypeFactory(),
                new FeatureFactory(),
                new FeatureSizeFactory(),
                new FloatProviderTypeFactory(),
                new FluidFactory(),
                new FluidIngredientTypeFactory(),
                new FluidTypeFactory(),
                new FoliagePlacerTypeFactory(),
                new GameEventFactory(),
                new GlobalLootModifierSerializerFactory(),
                new HeightProviderTypeFactory(),
                new HolderSetTypeFactory(),
                new IngredientTypeFactory(),
                new IntProviderTypeFactory(),
                new ItemSubPredicateTypeFactory(),
                new LootConditionTypeFactory(),
                new LootFunctionTypeFactory(),
                new LootNbtProviderTypeFactory(),
                new LootNumberProviderTypeFactory(),
                new LootPoolEntryTypeFactory(),
                new LootScoreProviderTypeFactory(),
                new MapDecorationTypeFactory(),
                new MaterialConditionFactory(),
                new MaterialRuleFactory(),
                new MemoryModuleTypeFactory(),
                new MenuFactory(),
                new MobEffectFactory(),
                new NumberFormatTypeFactory(),
                new ParticleTypeFactory(),
                new PlacementModifierTypeFactory(),
                new PointOfInterestTypeFactory(),
                new PositionSourceTypeFactory(),
                new PosRuleTestFactory(),
                new PotionFactory(),
                new RecipeSerializerFactory(),
                new RecipeTypeFactory(),
                new RootPlacerTypeFactory(),
                new RuleBlockEntityModifierFactory(),
                new RuleTestFactory(),
                new ScheduleFactory(),
                new SensorTypeFactory(),
                new SoundEventFactory(),
                new StatTypeFactory(),
                new StructureModifierSerializerFactory(),
                new StructurePieceFactory(),
                new StructurePlacementFactory(),
                new StructurePoolElementFactory(),
                new StructureProcessorFactory(),
                new StructureTypeFactory(),
                new TreeDecoratorTypeFactory(),
                new TriggerTypeFactory(),
                new TrunkPlacerTypeFactory(),
                new VillagerProfessionFactory(),
                new VillagerTypeFactory(),
                new InstrumentFactory(),
                new CatVariantFactory(),
                new DecoratedPotPatternFactory(),
                new FrogVariantFactory()
        );
    }
}